% Generated by MATLAB(R) 26.1 (R2026a) and 5G Toolbox 26.1 (R2026a).
% Generated on: 24-May-2026 10:00:35

%% Downlink 波形を生成しています
% Downlink 構成
cfgDL = nrDLCarrierConfig;
cfgDL.Label = 'NR-FR2-TM3.1';
cfgDL.FrequencyRange = 'FR2';
cfgDL.ChannelBandwidth = 100;
cfgDL.NCellID = 1;
cfgDL.NumSubframes = 10;
cfgDL.InitialNSubframe = 0;
cfgDL.WindowingPercent = 0;
cfgDL.SampleRate = 122880000;
cfgDL.CarrierFrequency = 28000000000;

%% SCS specific carriers
scscarrier = nrSCSCarrierConfig;
scscarrier.SubcarrierSpacing = 120;
scscarrier.NSizeGrid = 66;
scscarrier.NStartGrid = 0;

cfgDL.SCSCarriers = {scscarrier};

%% Bandwidth Parts
bwp = nrWavegenBWPConfig;
bwp.BandwidthPartID = 1;
bwp.Label = 'BWP1';
bwp.SubcarrierSpacing = 120;
bwp.CyclicPrefix = 'normal';
bwp.NSizeBWP = 66;
bwp.NStartBWP = 0;

cfgDL.BandwidthParts = {bwp};

%% Synchronization Signals Burst
ssburst = nrWavegenSSBurstConfig;
ssburst.Enable = false;
ssburst.Power = 0;
ssburst.BlockPattern = 'Case D';
ssburst.TransmittedBlocks = [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0];
ssburst.Period = 10;
ssburst.NCRBSSB = [];
ssburst.KSSB = 0;
ssburst.AntennaMapping = [];
ssburst.SSBlockPrecodingMatrix = [];
ssburst.DataSource = 'MIB';
ssburst.DMRSTypeAPosition = 2;
ssburst.CellBarred = false;
ssburst.IntraFreqReselection = false;
ssburst.PDCCHConfigSIB1 = 0;
ssburst.SubcarrierSpacingCommon = 60;

cfgDL.SSBurst = ssburst;

%% CORESET and Search Space Configuration
coreset = nrCORESETConfig;
coreset.CORESETID = 1;
coreset.Label = 'CORESET1';
coreset.FrequencyResources = 1;
coreset.Duration = 2;
coreset.CCEREGMapping = 'noninterleaved';
coreset.REGBundleSize = 6;
coreset.InterleaverSize = 2;
coreset.ShiftIndex = 0;
coreset.PrecoderGranularity = 'sameAsREG-bundle';
coreset.RBOffset = [];

cfgDL.CORESET = {coreset};

% Search Spaces
searchspace = nrSearchSpaceConfig;
searchspace.SearchSpaceID = 1;
searchspace.Label = 'SearchSpace1';
searchspace.CORESETID = 1;
searchspace.SearchSpaceType = 'common';
searchspace.StartSymbolWithinSlot = 0;
searchspace.SlotPeriodAndOffset = [1 0];
searchspace.Duration = 1;
searchspace.NumCandidates = [8 8 0 0 0];

cfgDL.SearchSpaces = {searchspace};

%% PDCCH Instances Configuration
pdcch = nrWavegenPDCCHConfig;
pdcch.Enable = true;
pdcch.Label = 'PDCCH1';
pdcch.Power = 0;
pdcch.BandwidthPartID = 1;
pdcch.SearchSpaceID = 1;
pdcch.AggregationLevel = 1;
pdcch.AllocatedCandidate = 1;
pdcch.CCEOffset = [];
pdcch.SlotAllocation = 0:7;
pdcch.Period = 10;
pdcch.AntennaMapping = [];
pdcch.PrecodingMatrix = [];
pdcch.Coding = false;
pdcch.DataBlockSize = 20;
pdcch.DataSource = 'PN23';
pdcch.RNTI = 0;
pdcch.DMRSScramblingID = 1;
pdcch.DMRSPower = 0;

cfgDL.PDCCH = {pdcch};

%% PDSCH Instances Configuration
% PDSCH 1
pdsch1 = nrWavegenPDSCHConfig;
pdsch1.Enable = true;
pdsch1.Label = 'Partial band PDSCH sequence with 64QAM modulation scheme (target, RNTI = 0) (Full downlink slots)';
pdsch1.Power = 0;
pdsch1.BandwidthPartID = 1;
pdsch1.Modulation = '64QAM';
pdsch1.NumLayers = 1;
pdsch1.MappingType = 'A';
pdsch1.ReservedCORESET = [];
pdsch1.SymbolAllocation = [0 14];
pdsch1.SlotAllocation = 0:6;
pdsch1.Period = 10;
pdsch1.PRBSet = 3:65;
pdsch1.PRBSetType = 'VRB';
pdsch1.VRBToPRBInterleaving = false;
pdsch1.VRBBundleSize = 2;
pdsch1.AntennaMapping = [];
pdsch1.PrecodingMatrix = [];
pdsch1.NID = [];
pdsch1.RNTI = 0;
pdsch1.Coding = true;
pdsch1.TargetCodeRate = 0.427734375;
pdsch1.TBScaling = 1;
pdsch1.XOverhead = 0;
pdsch1.LimitedBufferRateMatching = true;
pdsch1.MaxNumLayers = 8;
pdsch1.MCSTable = 'qam256';
pdsch1.RVSequence = 0;
pdsch1.DataSource = 'PN23';
pdsch1.DMRSPower = 0;
pdsch1.EnablePTRS = true;
pdsch1.PTRSPower = 0;

% PDSCH Reserved PRB
pdsch1ReservedPRB = nrPDSCHReservedConfig;
pdsch1ReservedPRB.PRBSet = [];
pdsch1ReservedPRB.SymbolSet = [];
pdsch1ReservedPRB.Period = [];

pdsch1.ReservedPRB = {pdsch1ReservedPRB};

% PDSCH DM-RS
pdsch1DMRS = nrPDSCHDMRSConfig;
pdsch1DMRS.DMRSConfigurationType = 1;
pdsch1DMRS.DMRSReferencePoint = 'CRB0';
pdsch1DMRS.DMRSTypeAPosition = 2;
pdsch1DMRS.DMRSAdditionalPosition = 0;
pdsch1DMRS.DMRSLength = 1;
pdsch1DMRS.CustomSymbolSet = [];
pdsch1DMRS.DMRSPortSet = [];
pdsch1DMRS.NIDNSCID = [];
pdsch1DMRS.NSCID = 0;
pdsch1DMRS.NumCDMGroupsWithoutData = 1;
pdsch1DMRS.DMRSDownlinkR16 = false;
pdsch1DMRS.DMRSEnhancedR18 = false;

pdsch1.DMRS = pdsch1DMRS;

% PDSCH PT-RS
pdsch1PTRS = nrPDSCHPTRSConfig;
pdsch1PTRS.TimeDensity = 4;
pdsch1PTRS.FrequencyDensity = 2;
pdsch1PTRS.REOffset = '00';
pdsch1PTRS.PTRSPortSet = [];

pdsch1.PTRS = pdsch1PTRS;

% PDSCH 2
pdsch2 = nrWavegenPDSCHConfig;
pdsch2.Enable = true;
pdsch2.Label = 'Partial band PDSCH sequence with 64QAM modulation scheme (target, RNTI = 2) (Full downlink slots)';
pdsch2.Power = 0;
pdsch2.BandwidthPartID = 1;
pdsch2.Modulation = '64QAM';
pdsch2.NumLayers = 1;
pdsch2.MappingType = 'A';
pdsch2.ReservedCORESET = [];
pdsch2.SymbolAllocation = [2 12];
pdsch2.SlotAllocation = 0:6;
pdsch2.Period = 10;
pdsch2.PRBSet = 0:2;
pdsch2.PRBSetType = 'VRB';
pdsch2.VRBToPRBInterleaving = false;
pdsch2.VRBBundleSize = 2;
pdsch2.AntennaMapping = [];
pdsch2.PrecodingMatrix = [];
pdsch2.NID = [];
pdsch2.RNTI = 2;
pdsch2.Coding = true;
pdsch2.TargetCodeRate = 0.427734375;
pdsch2.TBScaling = 1;
pdsch2.XOverhead = 0;
pdsch2.LimitedBufferRateMatching = true;
pdsch2.MaxNumLayers = 8;
pdsch2.MCSTable = 'qam256';
pdsch2.RVSequence = 0;
pdsch2.DataSource = 'PN23';
pdsch2.DMRSPower = 0;
pdsch2.EnablePTRS = true;
pdsch2.PTRSPower = 0;

pdschreserved = nrPDSCHReservedConfig;
pdschreserved.PRBSet = [];
pdschreserved.SymbolSet = [];
pdschreserved.Period = [];

pdsch2.ReservedPRB = {pdschreserved};

pdschdmrs = nrPDSCHDMRSConfig;
pdschdmrs.DMRSConfigurationType = 1;
pdschdmrs.DMRSReferencePoint = 'CRB0';
pdschdmrs.DMRSTypeAPosition = 2;
pdschdmrs.DMRSAdditionalPosition = 0;
pdschdmrs.DMRSLength = 1;
pdschdmrs.CustomSymbolSet = [];
pdschdmrs.DMRSPortSet = [];
pdschdmrs.NIDNSCID = [];
pdschdmrs.NSCID = 0;
pdschdmrs.NumCDMGroupsWithoutData = 1;
pdschdmrs.DMRSDownlinkR16 = false;
pdschdmrs.DMRSEnhancedR18 = false;

pdsch2.DMRS = pdschdmrs;

pdschptrs = nrPDSCHPTRSConfig;
pdschptrs.TimeDensity = 4;
pdschptrs.FrequencyDensity = 2;
pdschptrs.REOffset = '00';
pdschptrs.PTRSPortSet = [];

pdsch2.PTRS = pdschptrs;

% PDSCH 3
pdsch3 = nrWavegenPDSCHConfig;
pdsch3.Enable = true;
pdsch3.Label = 'Partial band PDSCH sequence with 64QAM modulation scheme (target, RNTI = 0) (Partial downlink slots)';
pdsch3.Power = 0;
pdsch3.BandwidthPartID = 1;
pdsch3.Modulation = '64QAM';
pdsch3.NumLayers = 1;
pdsch3.MappingType = 'A';
pdsch3.ReservedCORESET = [];
pdsch3.SymbolAllocation = [0 6];
pdsch3.SlotAllocation = 7;
pdsch3.Period = 10;
pdsch3.PRBSet = 3:65;
pdsch3.PRBSetType = 'VRB';
pdsch3.VRBToPRBInterleaving = false;
pdsch3.VRBBundleSize = 2;
pdsch3.AntennaMapping = [];
pdsch3.PrecodingMatrix = [];
pdsch3.NID = [];
pdsch3.RNTI = 0;
pdsch3.Coding = true;
pdsch3.TargetCodeRate = 0.427734375;
pdsch3.TBScaling = 1;
pdsch3.XOverhead = 0;
pdsch3.LimitedBufferRateMatching = true;
pdsch3.MaxNumLayers = 8;
pdsch3.MCSTable = 'qam256';
pdsch3.RVSequence = 0;
pdsch3.DataSource = 'PN23';
pdsch3.DMRSPower = 0;
pdsch3.EnablePTRS = true;
pdsch3.PTRSPower = 0;

pdschreserved = nrPDSCHReservedConfig;
pdschreserved.PRBSet = [];
pdschreserved.SymbolSet = [];
pdschreserved.Period = [];

pdsch3.ReservedPRB = {pdschreserved};

pdschdmrs = nrPDSCHDMRSConfig;
pdschdmrs.DMRSConfigurationType = 1;
pdschdmrs.DMRSReferencePoint = 'CRB0';
pdschdmrs.DMRSTypeAPosition = 2;
pdschdmrs.DMRSAdditionalPosition = 0;
pdschdmrs.DMRSLength = 1;
pdschdmrs.CustomSymbolSet = [];
pdschdmrs.DMRSPortSet = [];
pdschdmrs.NIDNSCID = [];
pdschdmrs.NSCID = 0;
pdschdmrs.NumCDMGroupsWithoutData = 1;
pdschdmrs.DMRSDownlinkR16 = false;
pdschdmrs.DMRSEnhancedR18 = false;

pdsch3.DMRS = pdschdmrs;

pdschptrs = nrPDSCHPTRSConfig;
pdschptrs.TimeDensity = 4;
pdschptrs.FrequencyDensity = 2;
pdschptrs.REOffset = '00';
pdschptrs.PTRSPortSet = [];

pdsch3.PTRS = pdschptrs;

% PDSCH 4
pdsch4 = nrWavegenPDSCHConfig;
pdsch4.Enable = true;
pdsch4.Label = 'Partial band PDSCH sequence with 64QAM modulation scheme (target, RNTI = 2) (Partial downlink slots)';
pdsch4.Power = 0;
pdsch4.BandwidthPartID = 1;
pdsch4.Modulation = '64QAM';
pdsch4.NumLayers = 1;
pdsch4.MappingType = 'A';
pdsch4.ReservedCORESET = [];
pdsch4.SymbolAllocation = [2 4];
pdsch4.SlotAllocation = 7;
pdsch4.Period = 10;
pdsch4.PRBSet = 0:2;
pdsch4.PRBSetType = 'VRB';
pdsch4.VRBToPRBInterleaving = false;
pdsch4.VRBBundleSize = 2;
pdsch4.AntennaMapping = [];
pdsch4.PrecodingMatrix = [];
pdsch4.NID = [];
pdsch4.RNTI = 2;
pdsch4.Coding = true;
pdsch4.TargetCodeRate = 0.427734375;
pdsch4.TBScaling = 1;
pdsch4.XOverhead = 0;
pdsch4.LimitedBufferRateMatching = true;
pdsch4.MaxNumLayers = 8;
pdsch4.MCSTable = 'qam256';
pdsch4.RVSequence = 0;
pdsch4.DataSource = 'PN23';
pdsch4.DMRSPower = 0;
pdsch4.EnablePTRS = true;
pdsch4.PTRSPower = 0;

pdschreserved = nrPDSCHReservedConfig;
pdschreserved.PRBSet = [];
pdschreserved.SymbolSet = [];
pdschreserved.Period = [];

pdsch4.ReservedPRB = {pdschreserved};

pdschdmrs = nrPDSCHDMRSConfig;
pdschdmrs.DMRSConfigurationType = 1;
pdschdmrs.DMRSReferencePoint = 'CRB0';
pdschdmrs.DMRSTypeAPosition = 2;
pdschdmrs.DMRSAdditionalPosition = 0;
pdschdmrs.DMRSLength = 1;
pdschdmrs.CustomSymbolSet = [];
pdschdmrs.DMRSPortSet = [];
pdschdmrs.NIDNSCID = [];
pdschdmrs.NSCID = 0;
pdschdmrs.NumCDMGroupsWithoutData = 1;
pdschdmrs.DMRSDownlinkR16 = false;
pdschdmrs.DMRSEnhancedR18 = false;

pdsch4.DMRS = pdschdmrs;

pdschptrs = nrPDSCHPTRSConfig;
pdschptrs.TimeDensity = 4;
pdschptrs.FrequencyDensity = 2;
pdschptrs.REOffset = '00';
pdschptrs.PTRSPortSet = [];

pdsch4.PTRS = pdschptrs;

cfgDL.PDSCH = {pdsch1,pdsch2,pdsch3,pdsch4};

%% CSI-RS Instances Configuration
csirs = nrWavegenCSIRSConfig;
csirs.Enable = false;
csirs.Label = 'CSIRS1';
csirs.Power = 0;
csirs.BandwidthPartID = 1;
csirs.CSIRSType = 'nzp';
csirs.CSIRSPeriod = 'on';
csirs.RowNumber = 3;
csirs.Density = 'one';
csirs.SymbolLocations = 0;
csirs.SubcarrierLocations = 0;
csirs.NumRB = 66;
csirs.RBOffset = 0;
csirs.AntennaMapping = [];
csirs.PrecodingMatrix = [];
csirs.NID = 1;

cfgDL.CSIRS = {csirs};

% 生成
[waveform,info] = nrWaveformGenerator(cfgDL);

Fs = info.ResourceGrids(1).Info.SampleRate; 								 % 波形のサンプル レートを Hz 単位で指定

%% 可視化
% Spectrum Analyzer
spectrum = spectrumAnalyzer(SampleRate=Fs, AveragingMethod='exponential', ForgettingFactor=1);
spectrum(waveform);
release(spectrum);


